More CI Testing

diff --git a/.github/workflows/build-and-release.yml b/.github/workflows/build-and-release.yml
--- a/.github/workflows/build-and-release.yml
+++ b/.github/workflows/build-and-release.yml
@@ -5,6 +5,9 @@ on:
     tags:
       - 'v*' # Trigger on version tags
 
+permissions:
+  contents: write # Ensure the token has write permissions to contents
+
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -45,24 +48,26 @@ jobs:
           name: app-package
           path: ./publish
 
-      - name: Create Release
-        uses: actions/create-release@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          tag_name: ${{ github.ref }}
-          release_name: Release ${{ github.ref }}
-          body: |
-            Release notes go here.
-          draft: false
-          prerelease: false
+      - name: Extract version
+        id: extract_version
+        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
+
+      - name: Get Release ID
+        id: get_release_id
+        run: |
+          release_id=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/tags/${GITHUB_REF#refs/tags/} | jq -r .id)
+          if [ "$release_id" == "null" ]; then
+            echo "Release not found"
+            exit 1
+          fi
+          echo "release_id=$release_id" >> $GITHUB_ENV
 
       - name: Upload Release Asset
         uses: actions/upload-release-asset@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
-          upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ./publish/zip/win32/x64/idleon-community-tool-win32-x64-0.0.0.zip # Adjust the path to your actual zip file
-          asset_name: idleon-community-tool-win32-x64-0.0.0.zip # Name of the file to appear in the release
+          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ env.release_id }}/assets?name=idleon-community-tool-win32-x64-${{ env.VERSION }}.zip
+          asset_path: ./publish/zip/win32/x64/idleon-community-tool-win32-x64-${{ env.VERSION }}.zip # Adjust the path to your actual zip file
+          asset_name: idleon-community-tool-win32-x64-${{ env.VERSION }}.zip # Name of the file to appear in the release
           asset_content_type: application/zip
